package mcptools

import (
	"encoding/json"
	"fmt"

	"github.com/worldline-go/types"
)

// Partial updates need to tell "the client omitted this property" from "the
// client sent an empty value". Elsewhere in krabby that distinction is carried
// by types.Null, which decodes the difference straight from the JSON.
//
// Tool arguments cannot use it: the MCP schema is generated by reflecting the
// argument struct, and a types.Null field reflects into an object with V and
// Valid properties — a shape no model should be asked to produce. The argument
// structs therefore stay plainly typed, and presence is recovered here from the
// raw arguments the client sent.

// argFields returns the properties present in a raw MCP argument object. An
// empty payload yields an empty set, not an error: it means "nothing sent".
func argFields(raw json.RawMessage) (map[string]json.RawMessage, error) {
	if len(raw) == 0 {
		return nil, nil
	}

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(raw, &fields); err != nil {
		return nil, fmt.Errorf("decode tool arguments; %w", err)
	}

	return fields, nil
}

// nullArg marks value as present only when the client sent name, so an omitted
// property reaches the service layer as "keep whatever is stored".
func nullArg[T any](fields map[string]json.RawMessage, name string, value T) types.Null[T] {
	if _, ok := fields[name]; !ok {
		return types.Null[T]{}
	}

	return types.NewNull(value)
}

// nullFromArgs is nullArg for a tool that only needs one nullable property.
func nullFromArgs[T any](raw json.RawMessage, name string, value T) (types.Null[T], error) {
	fields, err := argFields(raw)
	if err != nil {
		return types.Null[T]{}, err
	}

	return nullArg(fields, name, value), nil
}
