package manager

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/rytsh/krabby/internal/service/graphbuilder"
	"github.com/rytsh/krabby/internal/service/graphquery"
	"github.com/rytsh/krabby/internal/service/registry"
)

// BackfillGraphs removes Krabby's legacy managed ignore blocks and rebuilds
// tracked graphs generated by a different bag engine contract. Work is
// submitted to the bounded background queue and never blocks startup.
func (m *Manager) BackfillGraphs(ctx context.Context) {
	repos, err := m.reg.List(ctx)
	if err != nil {
		slog.Error("list repos for graph metadata backfill", "error", err)

		return
	}

	var stale []string
	for _, repo := range repos {
		if repo.Path == "" || !fileExists(filepath.Join(repo.Path, ".git")) {
			continue
		}

		// A rebuild only helps once a graph already exists.
		if !fileExists(graphbuilder.GraphPath(repo.Path)) {
			continue
		}

		if _, err := graphbuilder.RemoveLegacyManagedIgnore(repo.Path); err != nil {
			slog.Warn("remove legacy managed ignore block", "repo", repo.ID, "error", err)
		}

		if m.graphBuilder.GraphBuiltWithCurrentVersion(repo.Path) {
			continue
		}

		stale = append(stale, repo.ID)
	}

	if len(stale) == 0 {
		return
	}

	slog.Info("rebuilding graphs for current ignore rules and bag engine version",
		"graph_engine_version", m.graphBuilder.Version(), "repos", stale)

	var errs []error
	for _, id := range stale {
		if err := m.TriggerGenerate(id, []string{registry.StageGraph}, false); err != nil {
			errs = append(errs, fmt.Errorf("enqueue graph backfill for %s; %w", id, err))
		}
	}
	if err := errors.Join(errs...); err != nil {
		slog.Error("enqueue graph metadata backfills", "error", err)
	}
}

// CleanupMergedGraph removes a stale merged graph file left over from a run that
// had cross-repo merging enabled. It is a no-op when merging is enabled or no
// file exists. Prevents serving an outdated merged graph after merge is turned
// off.
func (m *Manager) CleanupMergedGraph() {
	if m.mergeEnabled || m.mergedPath == "" {
		return
	}

	if err := os.Remove(m.mergedPath); err != nil && !os.IsNotExist(err) {
		slog.Warn("remove stale merged graph", "path", m.mergedPath, "error", err)
	}
}

// rebuildMerged regenerates the cross-repo merged graph from all ready repos.
// It is a no-op when cross-repo merging is disabled (the default): independent
// repos produce no cross-repo edges, so the merged graph is just a costly
// disjoint union.
func (m *Manager) rebuildMerged(ctx context.Context) error {
	if !m.mergeEnabled {
		return nil
	}

	m.mergeMu.Lock()
	defer m.mergeMu.Unlock()

	repos, err := m.reg.List(ctx)
	if err != nil {
		return err
	}

	var graphs []string

	for _, r := range repos {
		gp := graphbuilder.GraphPath(r.Path)
		if fileExists(gp) {
			graphs = append(graphs, gp)
		}
	}

	switch len(graphs) {
	case 0:
		if err := os.Remove(m.mergedPath); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove empty merged graph; %w", err)
		}
	case 1:
		// Cross-repo merge needs >=2 inputs; single repo = copy.
		if err := graphquery.Validate(graphs[0]); err != nil {
			return fmt.Errorf("validate graph output before merge; %w", err)
		}
		if err := copyFile(graphs[0], m.mergedPath); err != nil {
			return fmt.Errorf("copy single graph; %w", err)
		}
	default:
		tmp := m.mergedPath + ".tmp"
		_ = os.Remove(tmp)
		if err := m.graphBuilder.MergeGraphs(ctx, tmp, graphs...); err != nil {
			_ = os.Remove(tmp)
			return err
		}
		if err := graphquery.Validate(tmp); err != nil {
			_ = os.Remove(tmp)
			return fmt.Errorf("validate merged graph output; %w", err)
		}
		if err := os.Rename(tmp, m.mergedPath); err != nil {
			_ = os.Remove(tmp)
			return fmt.Errorf("publish merged graph; %w", err)
		}
	}

	slog.Info("merged graph rebuilt", "repos", len(graphs), "out", m.mergedPath)

	return nil
}

// GraphPathFor resolves a repo id ("" = merged cross-repo graph) to a graph file.
func (m *Manager) GraphPathFor(ctx context.Context, repoID string) (string, error) {
	if repoID == "" {
		if !m.mergeEnabled {
			return "", fmt.Errorf("cross-repo merged graph is disabled; pass a repo id (enable it with bag.merge)")
		}

		if !fileExists(m.mergedPath) {
			return "", fmt.Errorf("merged graph not built yet; add repos and wait for builds")
		}

		return m.mergedPath, nil
	}

	repo, err := m.reg.Get(ctx, repoID)
	if err != nil {
		return "", err
	}

	if repo == nil {
		return "", fmt.Errorf("repo %s not found", repoID)
	}

	gp := graphbuilder.GraphPath(repo.Path)
	if !fileExists(gp) {
		return "", fmt.Errorf("graph for %s not built yet (status: %s)", repoID, repo.Status)
	}

	return gp, nil
}

// CallGraphTool answers a graph query tool call against the resolved graph using
// the in-process native engine (no python serve process is spawned). When repoID
// is empty the candidate graphs are restricted to namespace (empty or "default"
// selects the default bucket; NamespaceAll searches every namespace).
func (m *Manager) CallGraphTool(ctx context.Context, repoID, namespace, tool string, args map[string]any) (*mcp.CallToolResult, error) {
	repoID, selection, err := m.resolveGraphRepo(ctx, repoID, namespace, tool, args)
	if err != nil {
		return nil, err
	}
	if selection != "" {
		return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: selection}}}, nil
	}

	graphPath, err := m.GraphPathFor(ctx, repoID)
	if err != nil {
		return nil, err
	}

	text, err := m.engine.Call(graphPath, tool, args)
	if err != nil {
		return nil, err
	}

	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: text}}}, nil
}

func (m *Manager) graphRepoIDs(ctx context.Context, namespace string) ([]string, error) {
	repos, err := m.reg.List(ctx)
	if err != nil {
		return nil, err
	}

	ids := make([]string, 0, len(repos))
	for _, repo := range repos {
		if !repoInNamespace(repo, namespace) {
			continue
		}
		if fileExists(graphbuilder.GraphPath(repo.Path)) {
			ids = append(ids, repo.ID)
		}
	}
	sort.Strings(ids)

	return ids, nil
}

// repoInNamespace reports whether repo falls within the query namespace.
// NamespaceAll matches every repo; an empty or "default" query matches repos
// with no stored namespace; otherwise the stored namespace must match exactly.
func repoInNamespace(repo *registry.Repo, namespace string) bool {
	ns := strings.ToLower(strings.TrimSpace(namespace))
	if ns == registry.NamespaceAll {
		return true
	}
	if ns == "" || ns == registry.NamespaceDefault {
		return repo.Namespace == ""
	}

	return repo.Namespace == ns
}

// displayNamespace renders a namespace for messages, showing the default bucket
// as "default" rather than the empty stored form.
func displayNamespace(namespace string) string {
	ns := strings.ToLower(strings.TrimSpace(namespace))
	if ns == "" {
		return registry.NamespaceDefault
	}

	return ns
}

func inferRepoID(repoIDs []string, args map[string]any) string {
	var values []string
	for _, value := range args {
		if text, ok := value.(string); ok {
			values = append(values, text)
		}
	}
	haystack := normalizedMatchText(strings.Join(values, " "))

	match := ""
	for _, repoID := range repoIDs {
		name := repoID
		if slash := strings.LastIndex(name, "/"); slash >= 0 {
			name = name[slash+1:]
		}
		needle := normalizedMatchText(name)
		if len(needle) < 4 || !strings.Contains(haystack, needle) {
			continue
		}
		if match != "" {
			return ""
		}
		match = repoID
	}

	return match
}

func normalizedMatchText(value string) string {
	value = strings.ToLower(value)
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			return r
		}
		return -1
	}, value)
}

// graphRepoSelectionText explains that a graph query needs an explicit
// repository, listing a bounded set of candidates plus the tools that narrow
// them. Bounded because a namespace can hold hundreds of repos and the whole
// list would crowd out the instruction.
func graphRepoSelectionText(tool, namespace string, repoIDs []string) string {
	const maxShown = 20
	shown := repoIDs
	if len(shown) > maxShown {
		shown = shown[:maxShown]
	}

	text := fmt.Sprintf(
		"Repository selection required: cross-repository merge is disabled and %d repository graphs are available in namespace %s. Retry %s with repo set to one of: %s.",
		len(repoIDs), displayNamespace(namespace), tool, strings.Join(shown, ", "))
	if len(repoIDs) > len(shown) {
		text += " Use list_repos with search to find additional repository ids."
	}
	text += " If the question does not identify a repository, ask the user which one they mean; for symbol or source lookup, search_code can search across repositories first."

	return text
}

// GraphEngine exposes the native graph engine for in-process consumers (docgen).
func (m *Manager) GraphEngine() *graphquery.Engine { return m.engine }

// GraphEngineVersion returns the linked bag extraction contract version.
func (m *Manager) GraphEngineVersion() string {
	if m.graphBuilder == nil {
		return "unknown"
	}

	return m.graphBuilder.Version()
}

// MergedPath returns the merged cross-repo graph location ("" when merging is
// disabled or the graph is not built yet).
func (m *Manager) MergedPath() string {
	if !m.mergeEnabled || !fileExists(m.mergedPath) {
		return ""
	}

	return m.mergedPath
}
